# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/kacper/SystemyRekonfigurowalne/vp_bin/vp.srcs/sources_1/ip/dist_mem_gen_R/dist_mem_gen_R.xci
# IP: The module: 'dist_mem_gen_R' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/kacper/SystemyRekonfigurowalne/vp_bin/vp.srcs/sources_1/ip/dist_mem_gen_R/dist_mem_gen_R_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_mem_gen_R'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/kacper/SystemyRekonfigurowalne/vp_bin/vp.srcs/sources_1/ip/dist_mem_gen_R/dist_mem_gen_R.xci
# IP: The module: 'dist_mem_gen_R' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/kacper/SystemyRekonfigurowalne/vp_bin/vp.srcs/sources_1/ip/dist_mem_gen_R/dist_mem_gen_R_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_mem_gen_R'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
