# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lsriw/sr/SynowiecKacper/kacper_git2/SystemyRekonfigurowalne/good_vp/src/centroid_0_2/centroid_0.xci
# IP: The module: 'centroid_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/lsriw/sr/SynowiecKacper/kacper_git2/SystemyRekonfigurowalne/good_vp/src/centroid_0_2/src/c_addsub_0/c_addsub_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_addsub_0 || ORIG_REF_NAME==c_addsub_0} -quiet] -quiet

# IP: /home/lsriw/sr/SynowiecKacper/kacper_git2/SystemyRekonfigurowalne/good_vp/src/centroid_0_2/src/divider_32_20_0/divider_32_20_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==divider_32_20_0 || ORIG_REF_NAME==divider_32_20_0} -quiet] -quiet

# IP: /home/lsriw/sr/SynowiecKacper/kacper_git2/SystemyRekonfigurowalne/good_vp/src/centroid_0_2/src/divider_32_20_0/src/mult_32_20_lm/mult_32_20_lm.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_32_20_lm || ORIG_REF_NAME==mult_32_20_lm} -quiet] -quiet

# IP: /home/lsriw/sr/SynowiecKacper/kacper_git2/SystemyRekonfigurowalne/good_vp/src/centroid_0_2/centroid_0.xci
# IP: The module: 'centroid_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/lsriw/sr/SynowiecKacper/kacper_git2/SystemyRekonfigurowalne/good_vp/src/centroid_0_2/src/c_addsub_0/c_addsub_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_addsub_0 || ORIG_REF_NAME==c_addsub_0} -quiet] -quiet

# IP: /home/lsriw/sr/SynowiecKacper/kacper_git2/SystemyRekonfigurowalne/good_vp/src/centroid_0_2/src/divider_32_20_0/divider_32_20_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==divider_32_20_0 || ORIG_REF_NAME==divider_32_20_0} -quiet] -quiet

# IP: /home/lsriw/sr/SynowiecKacper/kacper_git2/SystemyRekonfigurowalne/good_vp/src/centroid_0_2/src/divider_32_20_0/src/mult_32_20_lm/mult_32_20_lm.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_32_20_lm || ORIG_REF_NAME==mult_32_20_lm} -quiet] -quiet
