# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/kacper/SystemyRekonfigurowalne/hdmi_vga_zybo_lut_good/hdmi_vga_zybo.srcs/sources_1/ip/vp_0_2/vp_0.xci
# IP: The module: 'vp_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/kacper/SystemyRekonfigurowalne/hdmi_vga_zybo_lut_good/hdmi_vga_zybo.srcs/sources_1/ip/vp_0_2/src/dist_mem_gen_R/dist_mem_gen_R.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dist_mem_gen_R || ORIG_REF_NAME==dist_mem_gen_R} -quiet] -quiet

# XDC: /home/kacper/SystemyRekonfigurowalne/hdmi_vga_zybo_lut_good/hdmi_vga_zybo.srcs/sources_1/ip/vp_0_2/src/dist_mem_gen_R/dist_mem_gen_R_ooc.xdc

# IP: /home/kacper/SystemyRekonfigurowalne/hdmi_vga_zybo_lut_good/hdmi_vga_zybo.srcs/sources_1/ip/vp_0_2/vp_0.xci
# IP: The module: 'vp_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/kacper/SystemyRekonfigurowalne/hdmi_vga_zybo_lut_good/hdmi_vga_zybo.srcs/sources_1/ip/vp_0_2/src/dist_mem_gen_R/dist_mem_gen_R.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dist_mem_gen_R || ORIG_REF_NAME==dist_mem_gen_R} -quiet] -quiet

# XDC: /home/kacper/SystemyRekonfigurowalne/hdmi_vga_zybo_lut_good/hdmi_vga_zybo.srcs/sources_1/ip/vp_0_2/src/dist_mem_gen_R/dist_mem_gen_R_ooc.xdc
