# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/lsriw/sr/SynowiecKacper/kacper_git2/SystemyRekonfigurowalne/hdmi_vga_zybo_YCbCr_bin/hdmi_vga_zybo.tmp/vp_v1_0_project/vp_v1_0_project.cache/wt [current_project]
set_property parent.project_path /home/lsriw/sr/SynowiecKacper/kacper_git2/SystemyRekonfigurowalne/hdmi_vga_zybo_YCbCr_bin/hdmi_vga_zybo.tmp/vp_v1_0_project/vp_v1_0_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_repo_paths {
  /home/lsriw/sr/SynowiecKacper/kacper_git2/SystemyRekonfigurowalne/hdmi_vga_ip_repo
  /home/lsriw/sr/SynowiecKacper/kacper_git2/SystemyRekonfigurowalne/rgb2ycbcr_ip
  /home/lsriw/sr/SynowiecKacper/kacper_git2/SystemyRekonfigurowalne/mux_ip
  /home/lsriw/sr/SynowiecKacper/kacper_git2/SystemyRekonfigurowalne/good_vp
  /home/lsriw/sr/SynowiecKacper/kacper_git2/SystemyRekonfigurowalne/my_ip_cores/ycbcr2bin_ip
  /home/lsriw/sr/SynowiecKacper/kacper_git2/SystemyRekonfigurowalne/centroid_ip
  /home/lsriw/sr/SynowiecKacper/kacper_git2/SystemyRekonfigurowalne/upel_ip_cores
} [current_project]
set_property ip_output_repo /home/lsriw/sr/SynowiecKacper/kacper_git2/SystemyRekonfigurowalne/hdmi_vga_zybo_YCbCr_bin/hdmi_vga_zybo.tmp/vp_v1_0_project/vp_v1_0_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/lsriw/sr/SynowiecKacper/kacper_git2/SystemyRekonfigurowalne/good_vp/src/vp.v
read_ip -quiet /home/lsriw/sr/SynowiecKacper/kacper_git2/SystemyRekonfigurowalne/good_vp/src/ycbcr2bin_0/ycbcr2bin_0.xci

read_ip -quiet /home/lsriw/sr/SynowiecKacper/kacper_git2/SystemyRekonfigurowalne/good_vp/src/rgb2ycbcr_0/rgb2ycbcr_0.xci

read_ip -quiet /home/lsriw/sr/SynowiecKacper/kacper_git2/SystemyRekonfigurowalne/good_vp/src/centroid_0_2/centroid_0.xci

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top vp -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef vp.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file vp_utilization_synth.rpt -pb vp_utilization_synth.pb"
