# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Users/Kacper/Documents/SystemyRekonfigurowalne/operations/operations.srcs/sources_1/ip/c_addsub_EF/c_addsub_EF.xci
# IP: The module: 'c_addsub_EF' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Users/Kacper/Documents/SystemyRekonfigurowalne/operations/operations.srcs/sources_1/ip/c_addsub_EF/c_addsub_EF_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_addsub_EF'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Users/Kacper/Documents/SystemyRekonfigurowalne/operations/operations.srcs/sources_1/ip/c_addsub_EF/c_addsub_EF.xci
# IP: The module: 'c_addsub_EF' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Users/Kacper/Documents/SystemyRekonfigurowalne/operations/operations.srcs/sources_1/ip/c_addsub_EF/c_addsub_EF_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_addsub_EF'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
