webtalk_init -webtalk_dir /home/kacper/SystemyRekonfigurowalne/operations/operations.sim/sim_1/behav/xsim/xsim.dir/tb_mainmodule_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Apr 21 22:40:14 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "6b6816fb-7c91-4fef-930c-e616786a5f62" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2b8fa505712d417b86f11a3fcfe303f0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "36" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "ManjaroLinux" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Manjaro Linux" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2168.482 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "30" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "891 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "25 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "227" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "44" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "6.47_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "370840_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1514629638 -regid "" -xml /home/kacper/SystemyRekonfigurowalne/operations/operations.sim/sim_1/behav/xsim/xsim.dir/tb_mainmodule_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/kacper/SystemyRekonfigurowalne/operations/operations.sim/sim_1/behav/xsim/xsim.dir/tb_mainmodule_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/kacper/SystemyRekonfigurowalne/operations/operations.sim/sim_1/behav/xsim/xsim.dir/tb_mainmodule_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
